### ISSUE TITLE
Invalid license change

### ISSUE THREAD

**Issue by spwhitton** [tsyrogit/zxcvbn-c#15]
You've changed the license for zxcvbn-c without the authorisation of the other individuals who contributed fixes and changes.

I hereby license my contributions to the Makefile under the MIT license.

I think that the only other contributions were not copyrightable, but it would be good if you can confirm.  This blocks me updating zxcvbn-c in Debian.

Thanks!

**Comment by tsyrogit** [comment]
I have had confirmations from the other contributors except for
- rchatterjee - I reverted his change just to be sure (cosmetic change to readme.md),
- kgoess - originally proposed the license change (so I assume he would be OK with it).

Change released as version 2.3.

**Comment by spwhitton** [comment]
Thank you for taking the time to follow up on this.  Will update
zxcvbn-c in Debian soon.

-- 
Sean Whitton
