### ISSUE TITLE
RPM Spec file?

### ISSUE THREAD

**Issue by erikogan** [tsyrogit/zxcvbn-c#24]
I’m building an RPM out of this library, and was wondering if you would accept a PR including the spec file, or if you thought it should live outside this repo?

I am building a PAM module using this library, so I could probably put both specs there if you would prefer.

Thanks for porting this to C, I’m excited to use it!

**Comment by tsyrogit** [comment]
I assume this is just adding a file which controls the RPM generation, which I think would be OK. I don't have a RPM base system so the details of this are unknown to me.
A requirement of this addition is to make sure it doesn't interfere with building on other types of systems. I know there is a Debian package and a Haskell wrapper, most likely there are other users.

**Comment by tsyrogit** [comment]
I have merged your pull request to implement this.
Thanks.
