### ISSUE TITLE
Please provide releases by means of signed git tags

### ISSUE THREAD

**Issue by spwhitton** [tsyrogit/zxcvbn-c#4]
It would be great to see some official stable releases of this code, using OpenPGP-signed git tags.

**Comment by tsyrogit** [comment]
I have added two tags 
v1.0 has the original code with your makefile mods
v2.0 adds some features that the original coffee script version has added over the last year

**Comment by spwhitton** [comment]
Thanks!

**Comment by spwhitton** [comment]
Thanks!  I'll package this for Debian soon.

-- 
Sean Whitton
